/**
 * BUG-019 pins for derivePhaseFromTail.
 *
 * The observed defect: a dashboard-spawned worker whose transcript
 * ends with /clear local-command records (type=user, never answered
 * by the model) reported phase='thinking' forever, and the tail
 * derive overrides the hook phase in both /sessions and anchor
 * tiles, so the tile showed a busy worker that was plainly idle.
 *
 * Pins:
 *   1. Trailing local-command user records (/clear) are walked past;
 *      the phase comes from the last REAL record instead.
 *   2. Trailing isMeta user records (local-command caveat) are
 *      walked past the same way.
 *   3. A real trailing user record on a FRESH file still derives
 *      'thinking' (live turn just submitted).
 *   4. A real trailing user record on a STALE file (untouched past
 *      TAIL_BUSY_MAX_AGE_MS) derives 'idle' -- a dead turn must not
 *      claim busy forever.
 *   5. Same staleness gate for assistant tool_use -> 'tool' only
 *      while fresh.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { derivePhaseFromTail } from '../src/dashboard/sessions.js';

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'phase-tail-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

function writeJsonl(records: object[], opts?: { staleMs?: number }): string {
  const file = path.join(tmpDir, 'session.jsonl');
  fs.writeFileSync(file, records.map((r) => JSON.stringify(r)).join('\n') + '\n');
  if (opts?.staleMs) {
    const t = new Date(Date.now() - opts.staleMs);
    fs.utimesSync(file, t, t);
  }
  return file;
}

const assistantText = {
  type: 'assistant',
  message: { role: 'assistant', content: [{ type: 'text', text: 'done.' }] },
};
const assistantTool = {
  type: 'assistant',
  message: {
    role: 'assistant',
    content: [{ type: 'tool_use', id: 'tu_1', name: 'Bash', input: {} }],
  },
};
const realUser = {
  type: 'user',
  message: { role: 'user', content: 'please fix the bug' },
};
const clearCommand = {
  type: 'user',
  message: {
    role: 'user',
    content:
      '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>',
  },
};
const caveatMeta = {
  type: 'user',
  isMeta: true,
  message: {
    role: 'user',
    content:
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
  },
};
const localCommandSystem = {
  type: 'system',
  subtype: 'local_command',
  content: '<local-command-stdout></local-command-stdout>',
};

describe('derivePhaseFromTail (BUG-019)', () => {
  it('walks past trailing /clear records and derives from the prior real record', () => {
    const file = writeJsonl([
      assistantText,
      caveatMeta,
      clearCommand,
      localCommandSystem,
    ]);
    expect(derivePhaseFromTail(file)).toBe('idle');
  });

  it('walks past isMeta user records', () => {
    const file = writeJsonl([assistantText, caveatMeta]);
    expect(derivePhaseFromTail(file)).toBe('idle');
  });

  it('still derives thinking for a fresh real user record', () => {
    const file = writeJsonl([assistantText, realUser]);
    expect(derivePhaseFromTail(file)).toBe('thinking');
  });

  it('derives idle (not thinking) for a real user record on a stale file', () => {
    const file = writeJsonl([assistantText, realUser], { staleMs: 10 * 60_000 });
    expect(derivePhaseFromTail(file)).toBe('idle');
  });

  it('derives tool for a fresh trailing tool_use, idle when stale', () => {
    const fresh = writeJsonl([realUser, assistantTool]);
    expect(derivePhaseFromTail(fresh)).toBe('tool');
    const staleFile = writeJsonl([realUser, assistantTool], {
      staleMs: 10 * 60_000,
    });
    expect(derivePhaseFromTail(staleFile)).toBe('idle');
  });

  it('derives idle for a trailing assistant text record regardless of age', () => {
    const file = writeJsonl([realUser, assistantText], { staleMs: 10 * 60_000 });
    expect(derivePhaseFromTail(file)).toBe('idle');
  });

  it('a /clear with no prior real record in the tail returns unknown', () => {
    const file = writeJsonl([caveatMeta, clearCommand, localCommandSystem]);
    expect(derivePhaseFromTail(file)).toBe('unknown');
  });
});
