/**
 * Wave 3 Lane B step 30 (LX-9). Thread-doc handoff.
 *
 * At session end, produces a pointer-style markdown document at
 * <DATA_ROOT>/lex/thread-docs/<brainstormId>.md. The doc captures
 * what was worked on, decisions reached, blockers encountered, and
 * who Claude is right now (context window state, active mode). It is
 * intentionally concise: pointers not full content. Lex dereferences
 * via /lex/sessions/:id and /lex/chunk-search when it needs detail.
 *
 * The document is generated by the configured LLM provider (same
 * path as self-audit and brainstorm distillation). If no provider is
 * configured, a summary is assembled from the existing session summary
 * text without LLM synthesis.
 *
 * Next-spawn loading: buildLexSystemPrompt() calls loadMostRecentThreadDoc()
 * and injects the result as a new 'threadDoc' prompt block between the
 * API surface and self-check layers. The block is only injected when a
 * thread doc exists and is < 7 days old.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { DATA_ROOT } from '../paths.js';
import { pickProvider } from '../llm/index.js';

const THREAD_DOCS_DIR = (): string =>
  path.posix.join(DATA_ROOT, 'lex', 'thread-docs');

const MAX_DOC_AGE_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

export interface ThreadDocInput {
  brainstormId: string;
  mode: string;
  userLabel: string | null;
  derivedLabel: string | null;
  /* Last rolling summary text produced by the session-end pipeline. */
  summaryText: string | null;
  /* Optional recent transcript text for LLM synthesis (max ~4k chars). */
  transcriptText?: string | null;
  turnCount: number;
  startedMs: number;
  endedMs: number | null;
}

export interface ThreadDocResult {
  filePath: string;
  generated: boolean;
  usedLlm: boolean;
  error?: string;
}

/* Build the pointer doc using the configured LLM provider, or fall
 * back to a structured summary from raw fields when no provider is
 * available. Either way the output lands in the same file. */
export async function writeThreadDoc(
  input: ThreadDocInput,
  log: (msg: string) => void = () => undefined,
): Promise<ThreadDocResult> {
  const dir = THREAD_DOCS_DIR();
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch {
    /* race with another caller; fine */
  }

  const filePath = path.posix.join(dir, `${input.brainstormId}.md`);
  const label =
    input.userLabel ?? input.derivedLabel ?? input.brainstormId.slice(0, 8);
  const startIso = new Date(input.startedMs).toISOString().slice(0, 16);
  const endIso = input.endedMs
    ? new Date(input.endedMs).toISOString().slice(0, 16)
    : 'ongoing';

  const provider = pickProvider();
  let docText: string;
  let usedLlm = false;

  if (provider && provider.isConfigured() && input.summaryText) {
    /* LLM path: synthesize a structured pointer doc from the rolling
     * summary (and optionally recent transcript turns if available). */
    const transcriptSection = input.transcriptText
      ? `\n\nRecent transcript excerpt (last turns):\n${input.transcriptText.slice(0, 3000)}`
      : '';
    const prompt =
      `You are writing a one-page pointer-style handoff doc for a Lex AI brainstorm session.\n` +
      `Session: "${label}" (mode=${input.mode}, ${input.turnCount} turns, ${startIso} to ${endIso})\n\n` +
      `Session summary:\n${input.summaryText.slice(0, 2000)}${transcriptSection}\n\n` +
      `Write a compact handoff doc with exactly these sections (keep each to 2-4 bullet points max):\n\n` +
      `# Thread doc: ${label}\n\n` +
      `## What we worked on\n` +
      `## Decisions reached\n` +
      `## Blockers / open questions\n` +
      `## Current state of Claude\n` +
      `(who Claude is right now: active work streams, steer queue, recent context)\n\n` +
      `## Pointers\n` +
      `(IDs or titles to dereference for full detail; not full content)\n\n` +
      `Rules: no em dashes, no en dashes. Use periods, commas, hyphens. ` +
      `Keep total under 400 words. This is a pointer doc, not a summary.`;

    try {
      const result = await provider.call('self_query', {
        systemBlocks: [
          {
            text: 'You write concise structured handoff notes for AI sessions. No em dashes, no en dashes. Under 400 words.',
            cache: false,
          },
        ],
        user: prompt,
        maxTokens: 600,
        temperature: 0.2,
      });
      docText = result.text.trim();
      usedLlm = true;
      log(`[thread-doc] LLM generated for brainstorm=${input.brainstormId} tokens_in=${result.inputTokens}`);
    } catch (err) {
      log(`[thread-doc] LLM failed, falling back to structured summary: ${(err as Error).message}`);
      docText = buildFallbackDoc(input, label, startIso, endIso);
    }
  } else {
    /* No-provider path: structured fallback from existing fields. */
    docText = buildFallbackDoc(input, label, startIso, endIso);
    log(`[thread-doc] no LLM provider; wrote structured fallback for brainstorm=${input.brainstormId}`);
  }

  try {
    fs.writeFileSync(filePath, docText, 'utf-8');
    return { filePath, generated: true, usedLlm };
  } catch (err) {
    const errMsg = (err as Error).message;
    log(`[thread-doc] write failed for brainstorm=${input.brainstormId}: ${errMsg}`);
    return { filePath, generated: false, usedLlm, error: errMsg };
  }
}

function buildFallbackDoc(
  input: ThreadDocInput,
  label: string,
  startIso: string,
  endIso: string,
): string {
  const summaryLines = input.summaryText
    ? input.summaryText
        .trim()
        .split('\n')
        .slice(0, 8)
        .map((l) => `- ${l.trim()}`)
        .join('\n')
    : '- (no summary available)';

  return [
    `# Thread doc: ${label}`,
    '',
    `Session: ${input.brainstormId}`,
    `Mode: ${input.mode}`,
    `Turns: ${input.turnCount}`,
    `Period: ${startIso} to ${endIso}`,
    '',
    '## What we worked on',
    summaryLines,
    '',
    '## Decisions reached',
    '- (synthesize from /lex/sessions/' + input.brainstormId + ' on demand)',
    '',
    '## Blockers / open questions',
    '- (check brainstorm chunks for unresolved items)',
    '',
    '## Current state of Claude',
    `- Mode at end: ${input.mode}`,
    `- Turn count: ${input.turnCount}`,
    '- Full transcript: GET /lex/sessions/' + input.brainstormId,
    '- Chunks: POST /lex/chunk-search { q: "<topic>" }',
    '',
    '## Pointers',
    `- Brainstorm ID: ${input.brainstormId}`,
    `- Label: ${label}`,
    `- Retrieval: POST /lex/recall { q: "${label}" }`,
  ].join('\n');
}

/* Load the most-recent thread doc for injection into the system prompt.
 * Returns null if no thread docs exist or all are older than MAX_DOC_AGE_MS. */
export function loadMostRecentThreadDoc(): string | null {
  const dir = THREAD_DOCS_DIR();
  if (!fs.existsSync(dir)) return null;
  let entries: { name: string; mtimeMs: number }[];
  try {
    entries = fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((e) => e.isFile() && e.name.endsWith('.md'))
      .map((e) => {
        const file = path.posix.join(dir, e.name);
        try {
          return { name: e.name, mtimeMs: fs.statSync(file).mtimeMs };
        } catch {
          return null;
        }
      })
      .filter((x): x is { name: string; mtimeMs: number } => Boolean(x))
      .sort((a, b) => b.mtimeMs - a.mtimeMs);
  } catch {
    return null;
  }
  if (entries.length === 0) return null;
  const newest = entries[0]!;
  if (Date.now() - newest.mtimeMs > MAX_DOC_AGE_MS) return null;
  const file = path.posix.join(dir, newest.name);
  try {
    return fs.readFileSync(file, 'utf-8');
  } catch {
    return null;
  }
}
